#!/bin/bash

# compilation of the algorithms
gcc -std=c11 -fopenmp -O3 -c assign/PSRS.c -o psrs.o -lm
gcc -std=c11 -O3 -c assign/main.c -o main.o
gcc -O3 -fopenmp main.o psrs.o -o parsort -lm

gcc -std=c11 -O3 sort.c -o sort


# printing the outputs of the algorithms
echo -n "Regular Algorithm: "
./sort $1 $2 | head -n1

echo  -n "Parallel Algorithm: "
./parsort $1 $2 | head -n1


# cleaning
rm sort
rm parsort
rm psrs.o
rm main.o
